"""widen properties.verification_status String(16) -> String(32)

The column was created at length 16 (migration c3d4e5f6a7b8) when the only coverage
values were 'pending' | 'monitored' | 'not_monitored' | 'unavailable' (≤13 chars).
The disambiguating resolver then introduced two longer values that are written into
this column verbatim by insar_verify_tasks (`prop.verification_status = result.coverage`,
an identity map):

  - 'needs_confirmation'  -> 18 chars  (overflows 16)
  - 'monitored_land'      -> 14 chars  (fits, but close)

On Postgres the 18-char write raises StringDataRightTruncation and rolls back the
ENTIRE verify task — exactly for the clustered-pin case the resolver exists to handle.
Widen to 32 (headroom for any future tier). Pure type widening: no data is lost,
every existing value still fits.

Hand-written (NOT autogenerated): `properties` is deliberately OUT of env.py
MANAGED_TABLES, so autogenerate never touches it. This explicit op.alter_column runs
regardless of the allow-list and touches ONLY this one column's type. Idempotent:
USING keeps existing values; re-running a 16->32 widen on an already-32 column is a
no-op widen. The live `commercial` DB (create_all-based, stale Alembic stamp) is
brought in line by the matching idempotent ALTER applied out-of-band; this migration
keeps the chain correct for any clean rebuild.

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-06-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8c9d0e1f2a3'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Widen only. existing_* lets Alembic emit a precise ALTER without consulting the
    # (allow-list-hidden) reflected table. No nullable/default change.
    op.alter_column(
        'properties', 'verification_status',
        existing_type=sa.String(length=16),
        type_=sa.String(length=32),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )


def downgrade() -> None:
    # Narrowing back to 16 would truncate any 'needs_confirmation' (18) rows and fail.
    # Only safe if no value currently exceeds 16 chars; guard so a downgrade never
    # corrupts data — it raises loudly instead.
    conn = op.get_bind()
    too_long = conn.execute(
        sa.text("SELECT COUNT(*) FROM properties "
                "WHERE char_length(verification_status) > 16")
    ).scalar()
    if too_long:
        raise RuntimeError(
            f"cannot narrow verification_status to 16: {too_long} row(s) hold a "
            "value longer than 16 chars (e.g. 'needs_confirmation'). Reclassify "
            "those listings before downgrading."
        )
    op.alter_column(
        'properties', 'verification_status',
        existing_type=sa.String(length=32),
        type_=sa.String(length=16),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
