"""listing verification_status + verified_at on properties

Adds two ADDITIVE columns to the legacy `properties` table so a listing can carry
its InSAR footprint-verification state (PE/work_flow.md §9 / misty-knitting-willow
plan, Part A):

  - verification_status : 'pending' | 'monitored' | 'not_monitored' | 'unavailable'
                          (the non-pending values match insar_resolver.COVERAGE_*).
                          server_default 'pending' so every existing row is honestly
                          "not yet checked", never an implied "safe". Part D's backfill
                          sweep corrects them in place afterwards.
  - verified_at         : when the last verification completed (NULL while pending).

Hand-written (NOT autogenerated): `properties` is deliberately excluded from the
env.py MANAGED_TABLES allow-list, so autogenerate never touches it. These op.add_column
calls run regardless of the allow-list and touch ONLY the two new columns. Zero DROP on
existing data; downgrade removes exactly what this migration added.

`now()`/server_default text is Postgres-only (same convention as the p4a/billing/
metering migrations); on SQLite (tests) the ORM `create_all` path supplies the default.

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2026-06-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'properties',
        sa.Column('verification_status', sa.String(length=16),
                  server_default='pending', nullable=False),
    )
    op.add_column(
        'properties',
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f('ix_properties_verification_status'), 'properties',
                    ['verification_status'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_properties_verification_status'), table_name='properties')
    op.drop_column('properties', 'verified_at')
    op.drop_column('properties', 'verification_status')
