"""p4a_integration_tables

Revision ID: e15260c80e9d
Revises: 25fdd2cab350
Create Date: 2026-06-22 13:34:47.254855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15260c80e9d'
down_revision: Union[str, Sequence[str], None] = '25fdd2cab350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('aoi_code', sa.String(length=64), nullable=False),
    sa.Column('insar_building_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_role', sa.String(length=32), nullable=False),
    sa.Column('recipient_ref', sa.String(length=255), nullable=True),
    sa.Column('danger_level', sa.SmallInteger(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('delivery_state', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash', name='uq_notification_audit_row_hash')
    )
    op.create_index('idx_notification_audit_building', 'notification_audit', ['aoi_code', 'insar_building_id'], unique=False)
    op.create_index(op.f('ix_notification_audit_aoi_code'), 'notification_audit', ['aoi_code'], unique=False)
    op.create_index(op.f('ix_notification_audit_created_at'), 'notification_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_audit_insar_building_id'), 'notification_audit', ['insar_building_id'], unique=False)
    op.create_table('building_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('aoi_code', sa.String(length=64), nullable=False),
    sa.Column('insar_building_id', sa.BigInteger(), nullable=False),
    sa.Column('match_method', sa.String(length=16), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'insar_building_id', name='uq_building_link_listing_building')
    )
    op.create_index('idx_building_link_aoi_building', 'building_link', ['aoi_code', 'insar_building_id'], unique=False)
    op.create_index(op.f('ix_building_link_aoi_code'), 'building_link', ['aoi_code'], unique=False)
    op.create_index(op.f('ix_building_link_insar_building_id'), 'building_link', ['insar_building_id'], unique=False)
    op.create_index(op.f('ix_building_link_listing_id'), 'building_link', ['listing_id'], unique=False)
    op.create_table('structural_flag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aoi_code', sa.String(length=64), nullable=False),
    sa.Column('insar_building_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_structural_flag_building_created', 'structural_flag', ['insar_building_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_structural_flag_aoi_code'), 'structural_flag', ['aoi_code'], unique=False)
    op.create_index(op.f('ix_structural_flag_created_at'), 'structural_flag', ['created_at'], unique=False)
    op.create_index(op.f('ix_structural_flag_granted_by'), 'structural_flag', ['granted_by'], unique=False)
    op.create_index(op.f('ix_structural_flag_insar_building_id'), 'structural_flag', ['insar_building_id'], unique=False)
    # ### end Alembic commands ###

    # ----------------------------------------------------------------------
    # APPEND-ONLY enforcement for the notification audit chain (legal evidence).
    # Autogenerate cannot infer this — it is the whole point of the table. Two
    # layers: a trigger that raises on ANY UPDATE/DELETE (defends against the app
    # role and ordinary owners), plus a REVOKE so the privilege isn't even granted.
    # An UPDATE or DELETE here would break the hash chain; we forbid both outright.
    # INSERT and SELECT remain allowed. TRUNCATE is also blocked by the trigger.
    # ----------------------------------------------------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION notification_audit_append_only()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'notification_audit is append-only: % is not permitted (legal audit chain)',
                TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_notification_audit_no_update
        BEFORE UPDATE OR DELETE OR TRUNCATE ON notification_audit
        FOR EACH STATEMENT EXECUTE FUNCTION notification_audit_append_only();
    """)
    # Best-effort REVOKE from the connecting role (defense in depth; the trigger is
    # the hard guarantee). Wrapped so a missing role name never fails the migration.
    op.execute("""
        DO $$
        BEGIN
            EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON notification_audit FROM %I', current_user);
        EXCEPTION WHEN OTHERS THEN
            NULL;  -- privilege model varies by deployment; the trigger still enforces it
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the append-only guard first (the trigger would otherwise block the
    # implicit cleanup and confuse a re-run); the function is dropped after.
    op.execute("DROP TRIGGER IF EXISTS trg_notification_audit_no_update ON notification_audit;")
    op.execute("DROP FUNCTION IF EXISTS notification_audit_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structural_flag_insar_building_id'), table_name='structural_flag')
    op.drop_index(op.f('ix_structural_flag_granted_by'), table_name='structural_flag')
    op.drop_index(op.f('ix_structural_flag_created_at'), table_name='structural_flag')
    op.drop_index(op.f('ix_structural_flag_aoi_code'), table_name='structural_flag')
    op.drop_index('idx_structural_flag_building_created', table_name='structural_flag')
    op.drop_table('structural_flag')
    op.drop_index(op.f('ix_building_link_listing_id'), table_name='building_link')
    op.drop_index(op.f('ix_building_link_insar_building_id'), table_name='building_link')
    op.drop_index(op.f('ix_building_link_aoi_code'), table_name='building_link')
    op.drop_index('idx_building_link_aoi_building', table_name='building_link')
    op.drop_table('building_link')
    op.drop_index(op.f('ix_notification_audit_insar_building_id'), table_name='notification_audit')
    op.drop_index(op.f('ix_notification_audit_created_at'), table_name='notification_audit')
    op.drop_index(op.f('ix_notification_audit_aoi_code'), table_name='notification_audit')
    op.drop_index('idx_notification_audit_building', table_name='notification_audit')
    op.drop_table('notification_audit')
    # ### end Alembic commands ###
